/* CONSULTA 21 - PROJETAR O TÍTULO DE TODOS OS CONTEÚDOS E A CATEGORIA ASSOCIADA  SEM USAR “INNER JOIN” */
SELECT C.TITULO, CAT.CATEGORIA
FROM CONTEUDO C, CATEGORIAS CAT
WHERE C.ID = CAT.ID_CONTEUDO;

/* CONSULTA 22 - PROJETAR O TÍTULO DE TODOS OS CONTEÚDOS E A CATEGORIA ASSOCIADA - USANDO “INNER JOIN” */
SELECT C.TITULO, CAT.CATEGORIA
FROM CONTEUDO C INNER JOIN CATEGORIAS CAT ON (C.ID = CAT.ID_CONTEUDO);

/* CONSULTA 23 - PROJETAR OS NOMES DE TODOS OS ARTISTAS E OS TÍTULOS DOS CONTEÚDOS EM QUE ATUARAM CUJA CLASSIFICAÇÃO SEJA 'Livre' OU '12 Anos' - SEM USAR “INNER JOIN” */
SELECT A.NOME, C.TITULO
FROM ARTISTA A, ELENCO E, CONTEUDO C
WHERE A.CPF = E.CPF AND 
      E.ID_CONTEUDO = C.ID AND 
      C.CLASSIFICACAO IN ('Livre', '12 Anos');

/* CONSULTA 24 - PROJETAR OS NOMES DE TODOS OS ARTISTAS E OS TÍTULOS DOS CONTEÚDOS EM QUE ATUARAM CUJA CLASSIFICAÇÃO SEJA 'Livre' OU '12 Anos' 
- USANDO “INNER JOIN” */
SELECT A.NOME, C.TITULO
FROM ARTISTA A INNER JOIN ELENCO E ON (A.CPF = E.CPF) 
     INNER JOIN CONTEUDO C ON (E.ID_CONTEUDO = C.ID)
WHERE C.CLASSIFICACAO IN ('Livre', '12 Anos');

/* CONSULTA 25 - PROJETAR TODOS OS CONTEÚDOS (TÍTULOS) E O ID DO VIDEO (SE HOUVER) */
SELECT C.TITULO, F.ID_VIDEO
FROM CONTEUDO C LEFT OUTER JOIN FILME F ON (C.ID = F.ID_CONTEUDO);

/* CONSULTA 26 - PROJETAR TODOS OS CONTEÚDOS (TÍTULOS) E O ID DO VIDEO (SE HOUVER) */
SELECT C.TITULO, F.ID_VIDEO
FROM FILME F RIGHT OUTER JOIN CONTEUDO C ON (C.ID = F.ID_CONTEUDO);

/* CONSULTA 27 - PROJETAR AS CONTAS (NOMES) E SEUS RESPECTIVOS DISPOSITIVOS (MODELOS), INCLUINDO AS CONTAS SEM DISPOSITIVOS E OS DISPOSITIVOS SEM CONTAS */
SELECT C.NOME, D.MODELO
FROM CONTA C FULL OUTER JOIN DISPOSITIVO D ON (C.EMAIL = D.EMAIL);

/* CONSULTA 28 - PROJETAR AS CONTAS (NOMES) SEM DISPOSITIVOS REGISTRADOS (NULL PARA MODELO) – USANDO “LEFT OUTER JOIN” */
SELECT C.NOME, D.MODELO
FROM CONTA C LEFT OUTER JOIN DISPOSITIVO D ON (C.EMAIL = D.EMAIL)
WHERE D.MODELO IS NULL;

/* CONSULTA 29 - PROJETAR AS CONTAS (NOMES) SEM DISPOSITIVOS REGISTRADOS (NULL PARA MODELO) - USANDO “RIGHT OUTER JOIN” */
SELECT C.NOME, D.MODELO
FROM DISPOSITIVO D RIGHT OUTER JOIN CONTA C ON (C.EMAIL = D.EMAIL)
WHERE D.MODELO IS NULL;

/* CONSULTA 30 - PROJETAR CONTAS SEM DISPOSITIVOS E DISPOSITIVOS SEM CONTAS VINCULADAS - USANDO “FULL OUTER JOIN” */
SELECT C.NOME, D.MODELO
FROM CONTA C FULL OUTER JOIN DISPOSITIVO D ON (C.EMAIL = D.EMAIL)
WHERE C.EMAIL IS NULL OR D.NUM_SERIE IS NULL;

/* CONSULTA 31 - PARA CADA ARTISTA, PROJETAR SEU NOME E 
OS NOMES DOS ARTISTAS MAIS NOVOS DO QUE ELE */
SELECT A1.NOME AS ARTISTA_MAIS_VELHO, A2.NOME AS ARTISTA_MAIS_NOVO
FROM ARTISTA A1 INNER JOIN ARTISTA A2 ON (A1.DATA_NASCIMENTO < A2.DATA_NASCIMENTO);

/* CONSULTA 32 - PROJETAR O NOME E O NASCIMENTO DOS ARTISTAS EM 
ORDEM DECRESCENTE DO NASCIMENTO. PARA DATAS IGUAIS, CONSIDERAR A ORDEM ALFABÉTICA DO NOME DO ARTISTA */
SELECT NOME, DATA_NASCIMENTO
FROM ARTISTA
ORDER BY DATA_NASCIMENTO DESC, NOME ASC;

/* CONSULTA 33 - PROJETAR A MÉDIA DE DURAÇÃO DOS VÍDEOS DOS FILMES POR CLASSIFICAÇÃO DO CONTEÚDO */
SELECT C.CLASSIFICACAO, AVG(V.DURACAO) AS MEDIA_DURACAO
FROM CONTEUDO C INNER JOIN FILME F ON (C.ID = F.ID_CONTEUDO)
     INNER JOIN VIDEO V ON (F.ID_VIDEO = V.ID)
GROUP BY C.CLASSIFICACAO;

/* CONSULTA 34 - PROJETAR AS CLASSIFICAÇÕES CUJAS MÉDIAS DE DURAÇÃO DOS FILMES SÃO MAIORES DO QUE 100 MINUTOS */
SELECT C.CLASSIFICACAO, AVG(V.DURACAO) AS MEDIA_DURACAO
FROM CONTEUDO C INNER JOIN FILME F ON (C.ID = F.ID_CONTEUDO)
     INNER JOIN VIDEO V ON (F.ID_VIDEO = V.ID)
GROUP BY C.CLASSIFICACAO 
HAVING AVG(V.DURACAO) > 100;

/* CONSULTA 35 - PROJETAR OS NOMES DAS CONTAS QUE POSSUEM MAIS DE 1 DISPOSITIVO REGISTRADO */
SELECT C.NOME, COUNT(*) AS QTD_DISPOSITIVOS
FROM CONTA C INNER JOIN DISPOSITIVO D ON (C.EMAIL = D.EMAIL) 
GROUP BY C.NOME
HAVING COUNT(*) > 1;

/* CONSULTA 36 - PROJETAR AS URLS DOS VÍDEOS COM DURAÇÃO ACIMA DA MÉDIA GERAL */
SELECT URL
FROM VIDEO
WHERE DURACAO > 
            (SELECT AVG(DURACAO)
             FROM VIDEO);

/* CONSULTA 37 - PROJETAR OS NOMES DOS ARTISTAS QUE NÃO INTERPRETAM PERSONAGENS MAIORES DE IDADE - USANDO “IN” E “INNER JOIN” */
SELECT NOME
FROM ARTISTA 
WHERE CPF NOT IN
                (SELECT I.CPF
                 FROM INTERPRETA I INNER JOIN PERSONAGEM P ON I.ID_PERSONAGEM = P.ID
                 WHERE P.IDADE >= 18);

/* CONSULTA 38 - PROJETAR OS NOMES DOS ARTISTAS QUE NASCERAM NO MESMO ANO E TÊM O MESMO GÊNERO DO ARTISTA DE CPF '111.111.111-11' */
SELECT NOME
FROM ARTISTA 
WHERE (GENERO, TO_CHAR(DATA_NASCIMENTO,'YY')) = 
            (SELECT GENERO, TO_CHAR(DATA_NASCIMENTO,'YY')
             FROM ARTISTA
             WHERE CPF = '111.111.111-11');
            
/* CONSULTA 39 - POR GÊNERO, PROJETAR O NOME E O GÊNERO DOS ARTISTAS MAIS VELHOS */
SELECT NOME, GENERO
FROM ARTISTA
WHERE (GENERO, TO_CHAR(DATA_NASCIMENTO,'YY')) IN 
     (SELECT GENERO, MIN(TO_CHAR(DATA_NASCIMENTO,'YY'))
      FROM ARTISTA
      GROUP BY GENERO)
ORDER BY GENERO;

/* CONSULTA 40 - PROJETAR OS NOMES DOS ARTISTAS QUE ATUAM NO CONTEÚDO ID 1 - USANDO “= ANY”, pois é equivalente ao “IN” */
SELECT NOME
FROM ARTISTA 
WHERE CPF = ANY
        (SELECT CPF
         FROM ELENCO
         WHERE ID_CONTEUDO = 1);

/* CONSULTA 41 - PROJETAR OS NOMES DOS ARTISTAS, EXCETO O DO MAIS VELHO */
SELECT NOME
FROM ARTISTA
WHERE DATA_NASCIMENTO > ANY 
      (SELECT DATA_NASCIMENTO
       FROM ARTISTA);

/* CONSULTA 42 - PROJETAR OS NOMES DOS ARTISTAS, EXCETO O DO MAIS IDOSO (MESMO RESULTADO DA ANTERIOR, LOGICA DIFERENTE) */
SELECT NOME
FROM ARTISTA
WHERE DATA_NASCIMENTO <>
      (SELECT MIN(DATA_NASCIMENTO)
       FROM ARTISTA);

/* CONSULTA 43 - PROJETAR AS URLS DOS VÍDEOS COM DURAÇÃO MAIOR DO QUE TODOS OS VÍDEOS DA SÉRIE ID 3 */
SELECT URL
FROM VIDEO
WHERE DURACAO > ALL
    (SELECT V.DURACAO
     FROM VIDEO V INNER JOIN EPISODIO E ON (V.ID = E.ID_VIDEO)
     WHERE E.ID_SERIE = 3);

/* CONSULTA 44 - PROJETAR AS URLS DOS VÍDEOS COM DURAÇÃO MAIOR DO QUE TODOS OS VÍDEOS DA SÉRIE ID 3 (USANDO MAX) */
SELECT URL
FROM VIDEO
WHERE DURACAO >
    (SELECT MAX(V.DURACAO)
     FROM VIDEO V INNER JOIN EPISODIO E ON (V.ID = E.ID_VIDEO)
     WHERE E.ID_SERIE = 3);

/* CONSULTA 45 - PROJETAR AS URLS DOS VÍDEOS COM DURAÇÃO ACIMA DA MÉDIA GERAL, MOSTRANDO QUANTOS MINUTOS ESTÁ ACIMA DA MÉDIA */
SELECT URL, DURACAO - (SELECT AVG(DURACAO) FROM VIDEO) AS MINUTOS_ACIMA_MEDIA
FROM VIDEO
WHERE DURACAO >
    (SELECT AVG(DURACAO)
     FROM VIDEO);

/* CONSULTA 46 - PROJETAR O PERCENTUAL DE CONTAS POR TIPO DE PLANO */
SELECT ID_PLANO, (QTD/(SELECT COUNT(*) FROM CONTA))*100 AS PERCENTUAL
FROM 
	(SELECT ID_PLANO, COUNT(*) AS QTD
	 FROM CONTA
	 GROUP BY ID_PLANO);

/* CONSULTA 47 - PROJETAR QUAIS SÃO OS PLANOS (IDs) QUE TÊM MAIS CONTAS DO QUE A MÉDIA GERAL DE CONTAS POR PLANO */
SELECT ID_PLANO, COUNT(*) AS QTD_CONTAS
FROM CONTA
GROUP BY ID_PLANO
HAVING COUNT(*) > 
            (SELECT AVG(QTD)
             FROM (SELECT ID_PLANO, COUNT(*) AS QTD 
                   FROM CONTA
                   GROUP BY ID_PLANO));

/* CONSULTA 48 - PROJETAR OS NOMES DOS PLANOS QUE POSSUEM CONTAS VINCULADAS */
SELECT DISTINCT P.NOME
FROM PLANO P INNER JOIN CONTA C ON (P.ID = C.ID_PLANO);

/* CONSULTA 49 - PROJETAR OS NOMES DOS PLANOS QUE POSSUEM CONTAS VINCULADAS – USANDO “EXISTS” */
SELECT P.NOME
FROM PLANO P
WHERE EXISTS 
        (SELECT * FROM CONTA C 
         WHERE C.ID_PLANO = P.ID);

/* CONSULTA 50 - PROJETAR OS NOMES DOS PLANOS QUE POSSUEM CONTAS VINCULADAS – USANDO “IN” */
SELECT P.NOME
FROM PLANO P
WHERE P.ID IN
        (SELECT C.ID_PLANO  
         FROM CONTA C 
         WHERE C.ID_PLANO IS NOT NULL);

/* CONSULTA 51 - PROJETAR OS TÍTULOS DOS EPISÓDIOS COM DURAÇÃO ABAIXO DA MÉDIA DE DURAÇÃO DOS EPISÓDIOS DA SUA PRÓPRIA SÉRIE (SUBCONSULTA CORRELACIONADA) */
SELECT E1.TITULO
FROM EPISODIO E1 INNER JOIN VIDEO V1 ON (E1.ID_VIDEO = V1.ID)
WHERE V1.DURACAO <  
            (SELECT AVG(V2.DURACAO)
             FROM EPISODIO E2 INNER JOIN VIDEO V2 ON (E2.ID_VIDEO = V2.ID)
             WHERE E1.ID_SERIE = E2.ID_SERIE);

/* CONSULTA 52 - PROJETAR OS NOMES DOS PLANOS SEM CONTAS VINCULADAS – USANDO “NOT EXISTS” */
SELECT P.NOME
FROM PLANO P
WHERE NOT EXISTS 
        (SELECT * FROM CONTA C 
         WHERE C.ID_PLANO = P.ID);

/* CONSULTA 53 - PROJETAR OS NOMES DOS PLANOS SEM CONTAS VINCULADAS – USANDO “NOT IN” */
SELECT P.NOME
FROM PLANO P
WHERE P.ID NOT IN
        (SELECT C.ID_PLANO 
         FROM CONTA C 
         WHERE C.ID_PLANO IS NOT NULL);

/* CONSULTA 54 - PROJETAR A CLASSIFICAÇÃO DA DURAÇÃO DOS VÍDEOS */
SELECT ID, DURACAO,
CASE 
    WHEN DURACAO >= 100 THEN 'LONGO'
    WHEN DURACAO >= 40 THEN 'MEDIO'
    ELSE 'CURTO'
END AS CLASSIFICACAO_DURACAO
FROM VIDEO;

