-------------------
-- CRIAÇÃO DO BD --
-------------------

-- CRIA TABELA PLANO
CREATE TABLE PLANO(
    ID NUMBER(10),
    NOME VARCHAR(80) NOT NULL,
    TIPO VARCHAR(30) NOT NULL,
    VALOR NUMBER(10,2),
    CONSTRAINT PK_PLANO PRIMARY KEY (ID)
);

-- CRIA TABELA CONTA
CREATE TABLE CONTA(
    EMAIL VARCHAR(100),
    NOME VARCHAR(80) NOT NULL,
    SENHA VARCHAR(50) NOT NULL,
    CARTAO_NUMERO VARCHAR(20),
    CARTAO_NOME VARCHAR(80),
    CARTAO_VALIDADE DATE,
    CARTAO_BANDEIRA VARCHAR(30),
    ID_PLANO NUMBER(10) NOT NULL,
    CONSTRAINT PK_CONTA PRIMARY KEY (EMAIL),
    CONSTRAINT FK_CONTA_PLANO FOREIGN KEY (ID_PLANO) REFERENCES PLANO(ID)
);

-- CRIA TABELA DISPOSITIVO
CREATE TABLE DISPOSITIVO(
    NUM_SERIE VARCHAR(50),
    MODELO VARCHAR(50),
    EMAIL VARCHAR(100),
    CONSTRAINT PK_DISPOSITIVO PRIMARY KEY (NUM_SERIE),
    CONSTRAINT FK_DISP_CONTA FOREIGN KEY (EMAIL) REFERENCES CONTA(EMAIL) ON DELETE CASCADE
);

-- CRIA TABELA PERFIL
CREATE TABLE PERFIL(
    EMAIL VARCHAR(100),
    NOME VARCHAR(50),
    TIPO VARCHAR(20),
    CONSTRAINT PK_PERFIL PRIMARY KEY (EMAIL, NOME),
    CONSTRAINT FK_PERFIL_CONTA FOREIGN KEY (EMAIL) REFERENCES CONTA(EMAIL) ON DELETE CASCADE
);

-- CRIA TABELA GERENCIA
CREATE TABLE GERENCIA(
    EMAIL VARCHAR(100),
    NOME_ADULTO VARCHAR(50),
    NOME_INFANTIL VARCHAR(50),
    CONSTRAINT PK_GERENCIA PRIMARY KEY (EMAIL, NOME_ADULTO, NOME_INFANTIL),
    CONSTRAINT FK_GERENCIA_ADULTO FOREIGN KEY (EMAIL, NOME_ADULTO) REFERENCES PERFIL(EMAIL, NOME) ON DELETE CASCADE,
    CONSTRAINT FK_GERENCIA_INFANTIL FOREIGN KEY (EMAIL, NOME_INFANTIL) REFERENCES PERFIL(EMAIL, NOME) ON DELETE CASCADE
);

-- CRIA TABELA CONTEUDO
CREATE TABLE CONTEUDO(
    ID NUMBER(10),
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(300),
    CLASSIFICACAO VARCHAR(20),
    DATA_LANCAMENTO DATE,
    CONSTRAINT PK_CONTEUDO PRIMARY KEY (ID)
);

-- CRIA TABELA CATEGORIAS
CREATE TABLE CATEGORIAS(
    ID_CONTEUDO NUMBER(4),
    CATEGORIA VARCHAR(50),
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID_CONTEUDO, CATEGORIA),
    CONSTRAINT FK_CAT_CONTEUDO FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID) ON DELETE CASCADE
);

-- CRIA TABELA VIDEO
CREATE TABLE VIDEO(
    ID NUMBER(10),
    DURACAO NUMBER(4), -- Duração em minutos
    URL VARCHAR(200),
    CONSTRAINT PK_VIDEO PRIMARY KEY (ID)
);

-- CRIA TABELA FILME
CREATE TABLE FILME(
    ID_CONTEUDO NUMBER(10),
    ID_VIDEO NUMBER(10),
    CONSTRAINT PK_FILME PRIMARY KEY (ID_CONTEUDO),
    CONSTRAINT AK_FILME_VIDEO UNIQUE (ID_VIDEO),
    CONSTRAINT FK_FILME_CONTEUDO FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_FILME_VIDEO FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO(ID)
);

-- CRIA TABELA SERIE
CREATE TABLE SERIE(
    ID_CONTEUDO NUMBER(10),
    CONSTRAINT PK_SERIE PRIMARY KEY (ID_CONTEUDO),
    CONSTRAINT FK_SERIE_CONTEUDO FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID) ON DELETE CASCADE
);

-- CRIA TABELA EPISODIO
CREATE TABLE EPISODIO(
    ID NUMBER(10),
    TITULO VARCHAR(100) NOT NULL,
    DESCRICAO VARCHAR(300),
    TEMPORADA NUMBER(2),
    DATA_LANCAMENTO DATE,
    ID_SERIE NUMBER(10) NOT NULL,
    ID_VIDEO NUMBER(10),
    CONSTRAINT PK_EPISODIO PRIMARY KEY (ID),
    CONSTRAINT AK_EPISODIO_VIDEO UNIQUE (ID_VIDEO),
    CONSTRAINT FK_EPI_SERIE FOREIGN KEY (ID_SERIE) REFERENCES SERIE(ID_CONTEUDO) ON DELETE CASCADE,
    CONSTRAINT FK_EPI_VIDEO FOREIGN KEY (ID_VIDEO) REFERENCES VIDEO(ID)
);

-- CRIA TABELA ARTISTA
CREATE TABLE ARTISTA(
    CPF VARCHAR(14),
    NOME VARCHAR(80) NOT NULL,
    GENERO VARCHAR(20),
    DATA_NASCIMENTO DATE,
    CONSTRAINT PK_ARTISTA PRIMARY KEY (CPF)
);

-- CRIA TABELA PERSONAGEM
CREATE TABLE PERSONAGEM(
    ID NUMBER(10),
    NOME VARCHAR(80) NOT NULL,
    GENERO VARCHAR(20),
    IDADE NUMBER(3),
    CONSTRAINT PK_PERSONAGEM PRIMARY KEY (ID)
);

-- CRIA TABELA ELENCO
CREATE TABLE ELENCO(
    ID_CONTEUDO NUMBER(10),
    CPF VARCHAR(14),
    CONSTRAINT PK_ELENCO PRIMARY KEY (ID_CONTEUDO, CPF),
    CONSTRAINT FK_ELENCO_CONTEUDO FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ELENCO_ARTISTA FOREIGN KEY (CPF) REFERENCES ARTISTA(CPF) ON DELETE CASCADE
);

-- CRIA TABELA INTERPRETA
CREATE TABLE INTERPRETA(
    ID_CONTEUDO NUMBER(10),
    CPF VARCHAR(14),
    ID_PERSONAGEM NUMBER(4),
    CONSTRAINT PK_INTERPRETA PRIMARY KEY (ID_CONTEUDO, CPF, ID_PERSONAGEM),
    CONSTRAINT FK_INT_ELENCO FOREIGN KEY (ID_CONTEUDO, CPF) REFERENCES ELENCO(ID_CONTEUDO, CPF) ON DELETE CASCADE,
    CONSTRAINT FK_INT_PERSONAGEM FOREIGN KEY (ID_PERSONAGEM) REFERENCES PERSONAGEM(ID) ON DELETE CASCADE
);

-- CRIA TABELA ASSISTE
CREATE TABLE ASSISTE(
    EMAIL VARCHAR(100),
    NOME VARCHAR(50),
    ID_CONTEUDO NUMBER(10),
    NUM_SERIE VARCHAR(50),
    DATA_ACESSO DATE,
    CONSTRAINT PK_ASSISTE PRIMARY KEY (EMAIL, NOME, ID_CONTEUDO, NUM_SERIE, DATA_ACESSO),
    CONSTRAINT FK_ASS_PERFIL FOREIGN KEY (EMAIL, NOME) REFERENCES PERFIL(EMAIL, NOME) ON DELETE CASCADE,
    CONSTRAINT FK_ASS_CONTEUDO FOREIGN KEY (ID_CONTEUDO) REFERENCES CONTEUDO(ID) ON DELETE CASCADE,
    CONSTRAINT FK_ASS_DISPOSITIVO FOREIGN KEY (NUM_SERIE) REFERENCES DISPOSITIVO(NUM_SERIE) ON DELETE CASCADE
);