---------------------
-- DELEÇÃO DAS TABELAS --
---------------------

DROP TABLE ASSISTE;
DROP TABLE INTERPRETA;
DROP TABLE GERENCIA;
DROP TABLE CATEGORIAS;
DROP TABLE EPISODIO;
DROP TABLE FILME;
DROP TABLE DISPOSITIVO;
DROP TABLE ELENCO;
DROP TABLE PERFIL;
DROP TABLE SERIE;
DROP TABLE CONTEUDO;
DROP TABLE CONTA;
DROP TABLE PLANO;
DROP TABLE VIDEO;
DROP TABLE ARTISTA;
DROP TABLE PERSONAGEM;